import i18n from "i18next";
import { initReactI18next } from "react-i18next";

// the translations
// (tip move them in a JSON file and import them,
// or even better, manage them separated from your code: https://react.i18next.com/guides/multiple-translation-files)
const resources = {
  en: {
    translation: {
      //Pagination
      next: "Next",
      previous: "Back",
      // Navigation / common
      welcomeMessage: "Welcome to React and react-i18next",
      dashboard: "Dashboard",
      statistics: "Statistics",
      allInventories: "All Inventories",
      adminPage: "Admin page",

      // Login
      login_title: "Inventory System",
      login_emailOrUsername: "Email or Username",
      login_password: "Password",
      login_signIn: "Sign in",
      login_noAccount: "Don't have an account?",
      login_signUpLink: "Sign up",

      // Register
      register_title: "Sign up",
      register_fullName: "Full Name",
      register_username: "Username",
      register_email: "Email",
      register_password: "Password",

      register_theme: "Theme",
      register_signUp: "Sign up",
      register_haveAccount: "Already have an account?",
      register_signInLink: "Sign in",

      // Dashboard
      dashboard_availableInventories: "Available Inventories",
      dashboard_searchInventories: "Search inventories...",
      dashboard_tags: "Tags",
      dashboard_searchResults: "Search Results",
      dashboard_noInventories: "No inventories found.",
      dashboard_noInventoriesWithTags: "No inventories with these tags.",
      public: "Public",
      private: "Private",
      yes: "Yes",
      no: "No",
      title: "Title",
      category: "Category",
      tags: "Tags",
      creator_username: "Creator",
      creator: "Creator",
      clear_tags: "Clear Tags",
      inventories_withTags: "Inventories with tags",
      description: "Description",
      name: "Name",

      // User page
      user_myInventories: "My Inventories",
      user_sharedWithMe: "Shared With Me",
      user_myProfile: "My Profile",
      user_searchMyInventories: "Search my inventories...",
      user_searchSharedInventories: "Search shared inventories...",
      user_profile_fullName: "Full Name",
      user_profile_language: "Language",
      user_profile_theme: "Theme",
      role: "Role",
      status: "Status",
      user_profile_newPassword: "New Password (leave blank to keep current)",
      user_profile_saveChanges: "Save Changes",
      username: "Username",
      email: "Email",
      fullName: "Full Name",
      language: "Language",
      theme: "Theme",
      newPassword: "New Password (leave blank to keep current)",
      saveChanges: "Save Changes",
      saving_dots: "Saving...",

      // Admin page
      admin_usersTab: "Users",
      admin_inventoriesTab: "Inventories",
      user_control: "Users Control",
      inventory_control: "Inventories Control",
      search_users: "Search Users",
      delete_users: "Delete selected users",
      update_user: "Update User",
      leave_blank: "leave blank to keep current",
      cancel: "Cancel",
      saving: "Saving...",
      save: "Save",
      admin: "Admin",
      user: "User",
      dark: "Dark",
      light: "Light",
      blocked: "Blocked",
      active: "Active",
      users: "Users",
      block_selected: "Block selected users",
      unblock_selected: "Unblock selected users",
      admin_selected: "Admin selected users",
      unadmin_selected: "Unadmin selected users",
      click_to_update: "Click to update user",
      username_cannot_change: "Username cannot be changed",
      email_cannot_change: "Email cannot be changed",

      // Statistics page
      statistics_topInventories: "Top Inventories",
      statistics_latestInventories: "Latest Inventories",
      statistics_noInventories: "No inventories found.",
      statistics_numOfItems: "Number of Items",

      // Inventory page
      inventory_itemsTab: "Items",
      inventory_discussionTab: "Discussion",
      inventory_settingsTab: "Settings",
      inventory_customIdTab: "Custom ID",
      inventory_accessTab: "Access",
      inventory_fieldsTab: "Fields",
      inventory_title: "Inventory",
      inventory_about: "About",
      inventory_items: "Items",
      inventory_discussion: "Discussion",
      inventory_about_tab: "About",
      inventory_searchItems: "Search items...",
      inventory_editInventory: "Edit Inventory",
      inventory_newItem: "+ New Item",
      inventory_deleteSelected: "Delete selected items",
      inventory_customId: "Custom Id",
      inventory_likes: "Likes",
      inventory_unlike: "Unlike",
      inventory_like: "Like",
      inventory_refresh: "Refresh",
      inventory_loadingComments: "Loading comments...",
      inventory_noComments: "No comments yet.",
      inventory_you: "You",
      inventory_userNum: "User",
      inventory_delete: "Delete",
      inventory_writeComment: "Write a comment...",
      inventory_send: "Send",
      inventory_visibility: "Visibility",
      inventory_noDescription: "No description",
      inventory_fields: "Fields",
      inventory_noFields: "No fields defined for this inventory.",
      inventory_shownInTable: "Shown in table",
      inventory_createNewItem: "Create New Item",
      inventory_create: "Create",
      inventory_editInv: "Edit Inventory",
      inventory_addField: "+ Add Field",
      inventory_addUser: "+ Add User",
      inventory_fieldTitle: "Title",
      inventory_fieldDescription: "Description",
      inventory_fieldType: "Type",
      inventory_showInTable: "Show in Table",
      inventory_existing: "Existing",
      inventory_noFieldsYet: "No fields yet.",
      inventory_usersWithAccess: "Users with Access",
      inventory_noUsersYet: "No users yet.",
      inventory_searchUserPlaceholder: "Search by username or email...",
      inventory_itemDetails: "Item Details",
      inventory_edit: "Edit",
      inventory_close: "Close",
      inventory_createdAt: "Created At",
      inventory_updatedAt: "Updated At",
      inventory_fieldValues: "Field Values",
      inventory_singleLinedText: "Single Lined Text",
      inventory_multiLinedText: "Multi Lined Text",
      inventory_number: "Number",
      inventory_boolean: "Boolean",
      inventory_link: "Link",
      inventory_tagsPlaceholder: "Type to search or add tags...",

      // User Page - Create Inventory Modal
      user_createNewInventory: "Create New Inventory",
      user_newInventory: "+ New Inventory",
      user_deleteSelectedInventories: "delete selected inventories",
      user_customIdFormat: "Custom ID Format",
      user_customIdDescription: "Define how item IDs will be auto-generated for this inventory.",
      user_fixedText: "Fixed Text",
      user_random20Bit: "Random 20-Bit",
      user_random32Bit: "Random 32-Bit",
      user_random6Digit: "Random 6-Digit",
      user_random9Digit: "Random 9-Digit",
      user_guid: "GUID",
      user_dateTime: "DateTime",
      user_sequence: "Sequence",
      user_type: "Type",
      user_value: "Value",
      user_format: "Format",
      user_addElement: "+ Add Element",
      user_preview: "Preview",
      user_noFieldsYet: "No fields yet. Click \"+ New Field\" to add one.",
      user_newField: "+ New Field",
      user_accessUser: "+ Access User",
      user_done: "Done",
      user_usersWithWriteAccess: "Users with write access",
      user_noUsersYet: "No users yet. Click \"+ Access Users\" to add one.",
      user_userLabel: "User",

      //Categories
      equipment: "Equipment",
      furniture: "Furniture",
      book: "Book",
      technology: "Technology",
      other: "Other"
    }
  },
  ru: {
    translation: {
      //Pagination
      next: "Вперед",
      previous: "Назад",

      // Navigation / common
      welcomeMessage: "Добро пожаловать в React и react-i18next",
      dashboard: "Панель",
      statistics: "Статистика",
      allInventories: "Все инвентари",
      adminPage: "Страница администратора",

      // Login
      login_title: "Система инвентаризации",
      login_emailOrUsername: "Email или имя пользователя",
      login_password: "Пароль",
      login_signIn: "Войти",
      login_noAccount: "Нет аккаунта?",
      login_signUpLink: "Зарегистрироваться",

      // Register
      register_title: "Регистрация",
      register_fullName: "Полное имя",
      register_username: "Имя пользователя",
      register_email: "Email",
      register_password: "Пароль",
      register_theme: "Тема",
      register_signUp: "Зарегистрироваться",
      register_haveAccount: "Уже есть аккаунт?",
      register_signInLink: "Войти",

      // Dashboard
      dashboard_availableInventories: "Доступные инвентари",
      dashboard_searchInventories: "Поиск инвентарей...",
      dashboard_tags: "Теги",
      public: "Публичный",
      private: "Приватный",
      dashboard_searchResults: "Результаты поиска",
      dashboard_noInventories: "Инвентари не найдены.",
      dashboard_noInventoriesWithTags: "Нет инвентарей с такими тегами.",
      yes: "Да",
      no: "Нет",
      title: "Название",
      category: "Категория",
      tags: "Теги",
      creator: "Создатель",
      creator_username: "Создатель",
      clear_tags: "Убрать теги",
      inventories_withTags: "Инвентари с тегами",
      description: "Описание",
      name: "Название",

      // User page
      user_myInventories: "Мои инвентари",
      user_sharedWithMe: "Поделились со мной",
      user_myProfile: "Мой профиль",
      user_searchMyInventories: "Поиск по моим инвентарям...",
      user_searchSharedInventories: "Поиск по общим инвентарям...",
      fullName: "Полное имя",
      role: "Роль",
      status: "Статус",
      language: "Язык",
      theme: "Тема",
      dark: "Темная",
      light: "Светлая",
      newPassword: "Новый пароль (оставьте пустым, чтобы не менять)",
      saveChanges: "Сохранить изменения",
      saving_dots: "Сохранение...",
      username: "Имя пользователя",
      email: "Email",

      // Admin page
      users: "Пользователи",
      admin_usersTab: "Пользователи",
      admin_inventoriesTab: "Инвентари",
      user_control: "Управление пользователями",
      inventory_control: "Управление инвентарями",
      search_users: "Искать пользователей",
      delete_users: "Удалить выбранных пользователей",
      update_user: "Обновить Пользователя",
      leave_blank: "Оставьте пустым чтобы сохранить текущую",
      cancel: "Отменить",
      saving: "Сохраняется...",
      save: "Сохранить",
      admin: "Админ",
      user: "Пользователь",
      blocked: "Заблокирован",
      active: "Активный",
      block_selected: "Заблокировать выбранных",
      unblock_selected: "Разблокировать выбранных",
      admin_selected: "Назначить администратором",
      unadmin_selected: "Снять права администратора",
      click_to_update: "Нажмите для обновления",
      username_cannot_change: "Имя пользователя нельзя изменить",
      email_cannot_change: "Email нельзя изменить",

      // Statistics page
      statistics_topInventories: "Топ инвентарей",
      statistics_latestInventories: "Последние инвентари",
      statistics_noInventories: "Инвентари не найдены.",
      statistics_numOfItems: "Количество элементов",

      // Inventory page
      inventory_itemsTab: "Элементы",
      inventory_discussionTab: "Обсуждение",
      inventory_settingsTab: "Настройки",
      inventory_customIdTab: "Пользовательский ID",
      inventory_accessTab: "Доступ",
      inventory_fieldsTab: "Поля",
      inventory_title: "Инвентарь",
      inventory_about: "О инвентаре",
      inventory_items: "Элементы",
      inventory_discussion: "Обсуждение",
      inventory_about_tab: "О инвентаре",
      inventory_searchItems: "Поиск элементов...",
      inventory_editInventory: "Редактировать",
      inventory_newItem: "+ Новый элемент",
      inventory_deleteSelected: "Удалить выбранные элементы",
      inventory_customId: "Пользовательский Id",
      inventory_likes: "Лайки",
      inventory_unlike: "Убрать лайк",
      inventory_like: "Лайк",
      inventory_refresh: "Обновить",
      inventory_loadingComments: "Загрузка комментариев...",
      inventory_noComments: "Комментариев пока нет.",
      inventory_you: "Вы",
      inventory_userNum: "Пользователь",
      inventory_delete: "Удалить",
      inventory_writeComment: "Написать комментарий...",
      inventory_send: "Отправить",
      inventory_visibility: "Видимость",
      inventory_noDescription: "Без описания",
      inventory_fields: "Поля",
      inventory_noFields: "Для этого инвентаря нет определённых полей.",
      inventory_shownInTable: "Показано в таблице",
      inventory_createNewItem: "Создать новый элемент",
      inventory_create: "Создать",
      inventory_editInv: "Редактировать инвентарь",
      inventory_addField: "+ Добавить поле",
      inventory_addUser: "+ Добавить пользователя",
      inventory_fieldTitle: "Название",
      inventory_fieldDescription: "Описание",
      inventory_fieldType: "Тип",
      inventory_showInTable: "Показать в таблице",
      inventory_existing: "Существующий",
      inventory_noFieldsYet: "Полей пока нет.",
      inventory_usersWithAccess: "Пользователи с доступом",
      inventory_noUsersYet: "Пользователей пока нет.",
      inventory_searchUserPlaceholder: "Поиск по имени или email...",
      inventory_itemDetails: "Детали элемента",
      inventory_edit: "Редактировать",
      inventory_close: "Закрыть",
      inventory_createdAt: "Создано",
      inventory_updatedAt: "Обновлено",
      inventory_fieldValues: "Значения полей",
      inventory_singleLinedText: "Однострочный текст",
      inventory_multiLinedText: "Многострочный текст",
      inventory_number: "Число",
      inventory_boolean: "Булево",
      inventory_link: "Ссылка",
      inventory_tagsPlaceholder: "Введите для поиска или добавления тегов...",

      // User Page - Create Inventory Modal
      user_createNewInventory: "Создать новый инвентарь",
      user_newInventory: "+ Новый инвентарь",
      user_deleteSelectedInventories: "Удалить выбранные инвентари",
      user_customIdFormat: "Формат пользовательского ID",
      user_customIdDescription: "Определите, как идентификаторы элементов будут автоматически генерироваться.",
      user_fixedText: "Фиксированный текст",
      user_random20Bit: "Случайный 20-бит",
      user_random32Bit: "Случайный 32-бит",
      user_random6Digit: "Случайные 6 цифр",
      user_random9Digit: "Случайные 9 цифр",
      user_guid: "GUID",
      user_dateTime: "Дата и время",
      user_sequence: "Последовательность",
      user_type: "Тип",
      user_value: "Значение",
      user_format: "Формат",
      user_addElement: "+ Добавить элемент",
      user_preview: "Предпросмотр",
      user_noFieldsYet: "Полей пока нет. Нажмите \"+ Новое поле\" чтобы добавить.",
      user_newField: "+ Новое поле",
      user_accessUser: "+ Пользователь",
      user_done: "Готово",
      user_usersWithWriteAccess: "Пользователи с правом записи",
      user_noUsersYet: "Пользователей пока нет. Нажмите \"+ Пользователь\" чтобы добавить.",
      user_userLabel: "Пользователь",

      //Categories
      equipment: "Оборудование",
      furniture: "Мебель",
      book: "Книга",
      technology: "Технология",
      other: "Другое"
    }
  }
};

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    lng: "ru", // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option

    interpolation: {
      escapeValue: false // react already safes from xss
    }
  });

export default i18n;