import requests
from odoo import models, fields, api, exceptions

class InventoryImport(models.Model):
    _name = 'inventory.import'
    _description = 'Imported Inventory'
    _rec_name = 'inventory_title'

    api_token = fields.Char(string='API Token', required=True, help="Token generated by the course project backend")
    inventory_title = fields.Char(string='Inventory Title', readonly=True)
    inventory_description = fields.Text(string='Inventory Description', readonly=True)
    statistic_ids = fields.One2many('inventory.import.statistic', 'import_id', string='Statistics', readonly=True)

    def action_import_data(self):
        for record in self:
            if not record.api_token:
                raise exceptions.UserError('API Token is required.')
            
            # Use the local backend URL for Docker to host communication, or replace with Railway live URL.
            # Usually the user is running the C# backend on localhost:5178 (or similar) or deployed on Railway.
            # Assuming Railway production API Backend URL based on app structure
            base_url = "https://itransitionprojectwork-production.up.railway.app" 
            
            endpoint = f"{base_url}/api/Inventory/stats?token={record.api_token}"
            
            try:
                response = requests.get(endpoint, timeout=10)
                if response.status_code != 200:
                    raise exceptions.UserError(f"Failed to fetch data from {endpoint}. Status Code: {response.status_code}")
                
                data = response.json()
                
                # The C# backend returns { "inventoryTitle": "...", "inventoryDescription": "...", "statistics": [...] }
                title = data.get('inventoryTitle', f"Imported Inventory {record.api_token[:5]}")
                desc = data.get('inventoryDescription', '')
                stats_data = data.get('statistics', [])
                
                record.inventory_title = title
                record.inventory_description = desc
                
                # Clear old statistics
                record.statistic_ids.unlink()
                
                # Parse new statistics
                stats_to_create = []
                for stat in stats_data:
                    popular_vals = stat.get('mostPopularValuesOfText', [])
                    popular_text = ", ".join(filter(None, popular_vals)) if popular_vals else ""
                    
                    stats_to_create.append((0, 0, {
                        'field_id_ref': stat.get('fieldId'),
                        'field_title': stat.get('fieldName'),
                        'max_number': stat.get('maxNumber'),
                        'min_number': stat.get('minNumber'),
                        'avg_number': stat.get('avgNumber'),
                        'popular_text_values': popular_text,
                    }))
                    
                record.write({
                    'statistic_ids': stats_to_create
                })
                
            except requests.exceptions.RequestException as e:
                raise exceptions.UserError(f"Network error while fetching API data: {str(e)}")


class InventoryImportStatistic(models.Model):
    _name = 'inventory.import.statistic'
    _description = 'Imported Inventory Statistic Field'

    import_id = fields.Many2one('inventory.import', string='Inventory Import', ondelete='cascade')
    field_id_ref = fields.Integer(string='Field ID')
    field_title = fields.Char(string='Field Title')
    
    max_number = fields.Float(string='Max Number')
    min_number = fields.Float(string='Min Number')
    avg_number = fields.Float(string='Avg Number')
    
    popular_text_values = fields.Char(string='Most Popular Values')
